### ISSUE TITLE
[RELEASE] mc  RELEASE.2023-09-20T15-22-31Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1009]
mc [RELEASE.2023-09-20T15-22-31Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-09-20T15-22-31Z) has changes that impact the docs:

- [x] Removes deprecated `mc admin heal` flags ([PR #4682](https://github.com/minio/mc/pull/4682))
- [x] Adds support for multiple policies in `mc admin user policy` command. This command is not currently documented. ([PR #4685](https://github.com/minio/mc/pull/4685))
- [x] Adds `--exclude-storageclass` flag to `mc mirror` ([PR #4684](https://github.com/minio/mc/pull/4684))

**Comment by djwfyi** [comment]
For #4682 flags, see also comments on #1005 .

**Comment by djwfyi** [comment]
For #4685, we don't currently document this command.
