### ISSUE TITLE
[RELEASE] DirectPV v4.0.9

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1034]
DirectPV [v4.0.9](https://github.com/minio/directpv/releases/tag/v4.0.9) has changes that impact the docs:

- [ ] There is a Helm chart for DirectPV ([PR #824](https://github.com/minio/directpv/pull/824))
- [ ] Adds commands to suspend or resume drives/volumes ([PR #842](https://github.com/minio/directpv/pull/842))
- [ ] Supports assigning volumes to unique disks ([PR #823](https://github.com/minio/directpv/pull/823))
- [ ] Corrects upgrade process ([PR #851](https://github.com/minio/directpv/pull/851))

**Comment by ravindk89** [comment]
@harshavardhana At some point we'd like to publish the DirectPV docs. I think everything is mostly ready - @djwfyi looks like https://github.com/minio/directpv-docs needs build-docs.sh.

Would be nice to wrap that out.

**Comment by djwfyi** [comment]
Added build-docs script in https://github.com/minio/directpv-docs/pull/5.
