### ISSUE TITLE
[RELEASE] mc  RELEASE.2023-10-04T06-52-56Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1035]
mc [RELEASE.2023-10-04T06-52-56Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-10-04T06-52-56Z) has changes that impact the docs:

- [ ] ~adds `--request-query` flag to `mc admin trace` ([PR #4704](https://github.com/minio/mc/pull/4704))~ 
- [ ] Adds `resource` as a metric type to `mc admin prometheus metrics` ([PR #4689](https://github.com/minio/mc/pull/4689))

MinIO Server [RELEASE.2023-10-07T15-07-38Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-10-07T15-07-38Z)

- [ ] Adds `resource` metric type ([PR #18057](https://github.com/minio/minio/pull/18057))

**Comment by feorlen** [comment]
Per @harshavardhana `mc admin trace --request-query` is intended for MinIO eng use. Discussing whether to hide it (and potentially others).
