### ISSUE TITLE
[RELEASE] Updates for three releases in mid-October

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1039]
## Server [RELEASE.2023-10-14T05-17-22Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-10-14T05-17-22Z)

- [x] Adds new counter events ([PR #18232](https://github.com/minio/minio/pull/18232))

## MC [RELEASE.2023-10-14T01-57-03Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-10-14T01-57-03Z)

- [x] Adds new flags to `mc admin trace` ([PR #4669](https://github.com/minio/mc/pull/4669))

## Operator [v5.0.10](https://github.com/minio/operator/releases/tag/v5.0.10)

- [x] Add buckets by modifying tenant YAML ([PR #1783](https://github.com/minio/operator/pull/1783))
- [x] Looks for `tls.crt` and `tls.key` files ([PR #1800](https://github.com/minio/operator/pull/1800))

**Comment by djwfyi** [comment]
#18232 - automatically handled by importing the event list

**Comment by djwfyi** [comment]
#1783 - we don't currently document modifying YAML directly. Not going to add in this pass.
