### ISSUE TITLE
[RELEASE] mc RELEASE.2023-10-24T05-18-28Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1045]
mc [RELEASE.2023-10-24T05-18-28Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-10-24T05-18-28Z) has changes that impact the docs:

- [x] New filter prevents duplicate transfers during `mv` and `cp` ([PR #4719](https://github.com/minio/mc/pull/4719))
- [x] mc flags can now have an ENV equivalent ([PR #4720](https://github.com/minio/mc/pull/4720))
- [x] `mc admin trace --stats` now shows min/max time ([PR #4723](https://github.com/minio/mc/pull/4723))
- [x] `mc admin trace --stats` now includes average time to first byte info ([PR #4726](https://github.com/minio/mc/pull/4726))
- [x] `mc mirror` now has a `--retry` flag ([PR #4715](https://github.com/minio/mc/pull/4715))
- [x] `mc admin replicate update` now has a `--bucket-bandwidth` flag ([PR #4687](https://github.com/minio/mc/pull/4687))

**Comment by djwfyi** [comment]
4719 fixes for expected behavior. Not documenting.

**Comment by djwfyi** [comment]
4723 and 4726 require PR #1065 first.
Or modify that PR to include these two items.

**Comment by djwfyi** [comment]
Update #1065 to include the --stats flag changes.
