### ISSUE TITLE
[RELEASE] mc RELEASE.2023-11-15T22-45-58Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1071]
mc [RELEASE.2023-11-15T22-45-58Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-11-15T22-45-58Z) has changes that impact the docs:

- [x] `mc admin` commands now support using STS tokens ([PR #4754](https://github.com/minio/mc/pull/4754))
- [x] `mc admin trace --stats` outputs an additional column of info ([PR #4757](https://github.com/minio/mc/pull/4757))
- [x] Adds `mc alias export` ([PR #4759](https://github.com/minio/mc/pull/4759))
- [ ] Additional mc environment variables ([PR #4763](https://github.com/minio/mc/pull/4763))

**Comment by ravindk89** [comment]
As per Harsha, do not document 4763 as it requires further refinement and fixups.
