### ISSUE TITLE
[RELEASE] mc RELEASE.2023-12-02T02-03-28Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1082]
mc [RELEASE.2023-12-02T02-03-28Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-12-02T02-03-28Z) has changes that impact the docs:

- [x] Add options to disable ilm expiry for site replication ([PR #4698](https://github.com/minio/mc/pull/4698))
- [x] Adds size based filters to `mc ilm rule add` ([PR #4770](https://github.com/minio/mc/pull/4770))
- [x] STS support is now alias specific ([PR #4771](https://github.com/minio/mc/pull/4771))
