### ISSUE TITLE
[RELEASE] MinIO Server RELEASE.2023-12-02T10-51-33Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1083]
MinIO Server [RELEASE.2023-12-02T10-51-33Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-12-02T10-51-33Z) has changes that impact the docs:

- [ ] Adds Websocket Grid functionality (but maybe not in the main docs; more for internal reference for now) ([PR #18461](https://github.com/minio/minio/pull/18461))
- [x] Adds snowball functionality to batch replicate jobs ([PR #18485](https://github.com/minio/minio/pull/18485))
   - [x] Related: adds ability for immediate tiering for snowball replication ([PR #18508](https://github.com/minio/minio/pull/18508))
- [ ] Adds ability to use external cache for GET/HEAD functions (for HDD drives primarily) ([PR #18239](https://github.com/minio/minio/pull/18239))
- [x] Relaxes batch limits for Kafka events ([PR #18513](https://github.com/minio/minio/pull/18513))
- [ ] Adds a drive max timeout ([PR #18501](https://github.com/minio/minio/pull/18501))
- [x] Adds support for an age conditional for bucket policies for pre-signed URLs ([PR #18529](https://github.com/minio/minio/pull/18529))
- [x] Additional Kafka variables for compression ([PR #18562](https://github.com/minio/minio/pull/18562))
- [x] Adds new expiration job type to the batch job framework ([PR #17946](https://github.com/minio/minio/pull/17946))

**Comment by ravindk89** [comment]
18329 needs to be handled separately.
