### ISSUE TITLE
MinIO Server RELEASE.2024-01-05T22-17-24Z

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1105]
MinIO Server [RELEASE.2024-01-05T22-17-24Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-01-05T22-17-24Z) has changes that impact the docs:

- [ ] New ILM metrics [PR #18731](https://github.com/minio/minio/pull/18731)
- [ ] New cluster health metric [PR #18736](https://github.com/minio/minio/pull/18736)

Unclear if docs needed:
- [ ] Hidden option to speed up scanner if no other drive requests at the time [PR #18734](https://github.com/minio/minio/pull/18734), [PR #18109](https://github.com/minio/minio/pull/18109)
- [ ] Is this a new value in the audit log? As in the [example log JSON here](https://min.io/docs/minio/linux/operations/monitoring/minio-logging.html#audit-log-structure) [PR #18737](https://github.com/minio/minio/pull/18737)

**Comment by feorlen** [comment]
Metrics should automatically populate, check that they did.

**Comment by ravindk89** [comment]
https://github.com/minio/minio/pull/19161/files will close PR18731, 18736 auto-sync.d

**Comment by ravindk89** [comment]
@vadmeste @shtripat with regards to

```
mc admin config get scanner idleSpeed
```

What, if any, guidance do we have on this? It's marked as hidden by default. [This comment](https://github.com/minio/minio/pull/18109#issuecomment-1874610378) mentions `delay` but that is marked as 'deprecated as of 2022' in the [comments](https://github.com/vadmeste/minio/blob/master/internal/config/scanner/scanner.go)

It looks like we default to '0' or 'on', but I cannot from the comments figure out what the intent here.

Does IdleMode = on mean we *do* sleep between incoming S3 requests? or that we *do not*?

**Comment by ravindk89** [comment]
For audit log, this only triggers in specific circumstances. Difficult to document. I did go ahead and update the structure based on what I could get.

**Comment by shtripat** [comment]
> @vadmeste @shtripat with regards to
> 
> ```
> mc admin config get scanner idleSpeed
> ```
> 
> What, if any, guidance do we have on this? It's marked as hidden by default. [This comment](https://github.com/minio/minio/pull/18109#issuecomment-1874610378) mentions `delay` but that is marked as 'deprecated as of 2022' in the [comments](https://github.com/minio/minio/blob/master/internal/config/scanner/scanner.go)
> 
> It looks like we default to '0' or 'on', but I cannot from the comments figure out what the intent here.
> 
> Does IdleMode = on mean we _do_ sleep between incoming S3 requests? or that we _do not_?

IIUC IdelMode `on` means we sleep by default between S3 calls. @vadmeste can confirm the same.

**Comment by harshavardhana** [comment]
idle_speed=off (would simply avoid any idling when there are no requests)


We default to `idling` to sleep between objects regardless of incoming S3 requests.

**Comment by ravindk89** [comment]
I think we're done here - we do not document hidden fields.
