### ISSUE TITLE
[RELEASE] Operator v5.0.12

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1129]
Operator [v5.0.12](https://github.com/minio/operator/releases/tag/v5.0.12) has changes that impact the docs:

- [ ] ~Multitenancy support for external certs [PR #1971](https://github.com/minio/operator/pull/1971R)
       Check with @cniackz  about impacts on a user.~ More work needed before this is complete and ready for customers.
- [ ] ~Edit pools when multiple pools exist [PR #1953](https://github.com/minio/operator/pull/1953)
        Likely just a note that we have improved support.~ No docs yet for managing pools with Operator Console, see https://github.com/minio/docs/issues/1174
- [x] New kubectl flags [PR #1907](https://github.com/minio/operator/pull/1907)/[PR #1926](https://github.com/minio/operator/pull/1926)
- [ ] ~Helm chart allows annotations for PVCs [PR #1897](https://github.com/minio/operator/pull/1897)~ no doc update needed

**Comment by feorlen** [comment]
FYI: kubectl flags also need a once-over to ensure we still have current information documented.

**Comment by feorlen** [comment]
Cert manager behavior may block this issue, need to clarify with eng.

**Comment by feorlen** [comment]
For Helm chart annotations, there was already support for annotations for pods. This adds another thing you can annotate (`storageAnnotations`).
Both sections in `tenant/values.yaml` link to the Kubernetes docs about annotations. Since we aren't adding more detailed docs about working with Helm charts, seems this is sufficient.

**Comment by feorlen** [comment]
Web docs were previously updated from `tenant volume add` to `tenant expand`

**Comment by feorlen** [comment]
last item completed in https://github.com/minio/docs/pull/1171
