### ISSUE TITLE
[RELEASE] mc RELEASE.2024-02-24T01-33-20Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1140]
mc [RELEASE.2024-02-24T01-33-20Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-02-24T01-33-20Z) has changes that impact the docs:

- [x] Adds `mc put` command to upload from local to S3 target [PR #4839](https://github.com/minio/mc/pull/4839)
        See also [PR 4849](https://github.com/minio/mc/pull/4849) for error messages added for the command.
        Distinguish from `mc cp`.
- [x] Adds `mc get` command to download to local from S3 source [PR #4847](https://github.com/minio/mc/pull/4847)
        Distinguish from `mc cp`.
- [x] Adds `--expire-all-object-versions` flag to `mc ilm rule add` [PR #4840](https://github.com/minio/mc/pull/4840)
        Requires MinIO Server [PR 19095](https://github.com/minio/minio/pull/19095), included in [MinIO Server RELEASE.2024-02-26T09-33-48Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-02-26T09-33-48Z)
       Make sure to distinguish from the `--noncurrentVersionExpiration` flag.
