### ISSUE TITLE
[RELEASE] mc  RELEASE.2024-03-03T00-13-08Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1143]
mc [RELEASE.2024-03-03T00-13-08Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-03-03T00-13-08Z) has changes that impact the docs:

- [x] `mc replicate add` and `mc replicate update` now supports using an alias [PR #4864](https://github.com/minio/mc/pull/4864)
- [x] Adds support for excluding buckets to `mc mirror` [PR #4861](https://github.com/minio/mc/pull/4861)
- [x] `mc support` commands now support `--json` output [PR #4859](https://github.com/minio/mc/pull/4859)

**Comment by djwfyi** [comment]
Nothing to change in the docs for 4859.
