### ISSUE TITLE
[RELEASE] MinIO Server RELEASE.2024-03-03T17-50-39Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1144]
MinIO Server [RELEASE.2024-03-03T17-50-39Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-03-03T17-50-39Z) has changes that impact the docs:

- [x] `userCredentials` setting added for NATS notifications [PR #19139](https://github.com/minio/minio/pull/19139)
- [x] With the latest KES, root credentials can be automatically generated if a KMS is enabled [PR #19025](https://github.com/minio/minio/pull/19025)
- [x] Adds new configs for expiring tiered objects [PR #18926](https://github.com/minio/minio/pull/18926)
