### ISSUE TITLE
[RELEASE] Server RELEASE.2024-03-15T01-07-19Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1159]
Server [RELEASE.2024-03-15T01-07-19Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-03-15T01-07-19Z) has changes that impact the docs:

- [ ] New v3 of metrics system combines metrics in smaller, different chunks; check how metrics are imported and update as needed [PR #19068](https://github.com/minio/minio/pull/19068)
- [ ] Changes how compression variables are handled, now accepting `*` as an valid setting [PR #19234](https://github.com/minio/minio/pull/19234)
- [ ] Allows configuration of the max objects per version limit [PR #19265](https://github.com/minio/minio/pull/19265)
- [ ] New "optimized" envvar for configuring parity settings when drives go offline; sets to maximize space rather than reducing data drives to retain parity [PR #19260](https://github.com/minio/minio/pull/19260)

**Comment by ravindk89** [comment]
Note: Metrics V3 is being actively reworked, we can leave that off for now.
