### ISSUE TITLE
[RELEASE] MinIO/MC  RELEASE.2024-07-04

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1260]
MinIO Server [RELEASE.2024-07-04T14-25-45Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-07-04T14-25-45Z) and MinIO Client [RELEASE.2024-07-03T20-17-25Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-07-03T20-17-25Z) have changes that impact the docs:

- [x] Adds API for tracking status of batch jobs [PR #19679](https://github.com/minio/minio/pull/19679) and [PR #4930](https://github.com/minio/mc/pull/4930)
- [x] Removes `mc license update` [PR #20037](https://github.com/minio/minio/pull/20037)
- [x] Adds ability to use `mc ilm tier update` for Azure credentials [PR #4975](https://github.com/minio/mc/pull/4975)
