### ISSUE TITLE
[RELEASE] mc RELEASE.2024-07-03T20-17-25Z and  RELEASE.2024-07-15T17-46-06Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1270]
MinIO Client [RELEASE.2024-07-03T20-17-25Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-07-03T20-17-25Z) and [RELEASE.2024-07-15T17-46-06Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-07-15T17-46-06Z) have changes that impact the docs:

- [x] Adds new `mc batch status` command [PR #4930](https://github.com/minio/mc/pull/4930)
- [x] Allow updating Azure credentials [PR #4975](https://github.com/minio/mc/pull/4975)
- [x] `mc mirror --watch` looks to `statusCh` for when to resume operations after a drive failure; restore `--skip-errors` flag [PR #4986](https://github.com/minio/mc/pull/4986)

**Comment by feorlen** [comment]
Fyi customer is asking about docs for `mc ilm tier` and Azure from https://github.com/minio/mc/pull/4930

**Comment by djwfyi** [comment]
4930 and 4975 completed in PR #1299 as part of docs issue #1260.
