### ISSUE TITLE
[RELEASE] Several MinIO Server releases

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1271]
MinIO Server [RELEASE.2024-07-13T01-46-15Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-07-13T01-46-15Z) has changes that impact the docs:

- [x] Removes or hides several fields related to `get` and  [PR #20069](https://github.com/minio/minio/pull/20069)

MinIO Server [RELEASE.2024-07-10T18-41-49Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-07-10T18-41-49Z) has changes that impact the docs:

- [x] Updates to remove delete marker example ILM rule [PR #20056](https://github.com/minio/minio/pull/20056)
- [x] Adds groups to LDAP policy entities [PR #20052](https://github.com/minio/minio/pull/20052)

MinIO Server [RELEASE.2024-07-04T14-25-45Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-07-04T14-25-45Z) has changes that impact the docs:

- [x] Removes `license update` job [PR #20037](https://github.com/minio/minio/pull/20037)

**Comment by djwfyi** [comment]
#20037 was removed as part of PR #1299 .
#20056 did not impact docs.
