### ISSUE TITLE
[RELEASE] Operator v6.0.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1273]
Operator [v6.0.0](https://github.com/minio/operator/releases/tag/v6.0.0) has changes that impact the docs:

Note that [PR #2141](https://github.com/minio/operator/pull/2141) contains some documentation for v6.0.0.

- [ ] Health info (color scheme) is added to info about tenants ([PR #2116](https://github.com/minio/operator/pull/2116))
- [ ] Sidecar is its own container, reducing the need for rolling restarts ([PR #2105](https://github.com/minio/operator/pull/2105))
- [ ] Secrets stay in the Operator namespace and no longer copy to the tenant ([PR #2133](https://github.com/minio/operator/pull/2133))
- [ ] Updated GitHub docs on TLS certificate flow with cert manager ([PR #2079](https://github.com/minio/operator/pull/2079) and [PR #2154](https://github.com/minio/operator/pull/2154))
- [ ] Allow for seconds in K8s tolerations ([PR #2168](https://github.com/minio/operator/pull/2168))
- [ ] Tokens verified directly with K8s instead of with MinIO ([PR #2166](https://github.com/minio/operator/pull/2166))
- [ ] Sidecar has been split out and now requires its own image info in the Helm chart ([PR #2176](https://github.com/minio/operator/pull/2176))
- [ ] Envvar moved to sidecar (this works in conjunction with #2176) ([PR #2221](https://github.com/minio/operator/pull/2221))
- [ ] Adds a tenant readiness endpoint ([PR #2183](https://github.com/minio/operator/pull/2183))
- [ ] Adds MinIO Job documentation to GitHub ([PR #2173](https://github.com/minio/operator/pull/2173))
- [ ] Deleting a tenant's storage now requires a manual task for k8s consistency ([PR #2203](https://github.com/minio/operator/pull/2203))
- [ ] Removes the Operator GUI UI ([PR #2205](https://github.com/minio/operator/pull/2205))
- [ ] Adds ability to expand a PVC ([PR #2196](https://github.com/minio/operator/pull/2196))
- [ ] Removes the field `.spec.credsSecret` in favor of `.spec.configuration` in tenant specs ([PR #2217](https://github.com/minio/operator/pull/2217))

**Comment by djwfyi** [comment]
We do not discuss checking tenant health anywhere at the moment.
Skipping 2116.

**Comment by djwfyi** [comment]
2168 is a bugfix; nothing to document.

**Comment by djwfyi** [comment]
2176 automatically covered with the Helm chart integration.

**Comment by feorlen** [comment]
Nothing required for https://github.com/minio/operator/pull/2166, removed from current content along with other Operator Console instructions. Remaining references are all from deprecated instructions.

**Comment by ravindk89** [comment]
UI has been mostly removed, or possibly entirely removed. There may be trailing non-linked references that did not come up in grep though (or on orphaned pages, or related to the tenant console).
