### ISSUE TITLE
[RELEASE] Server/MC 2024-09-09 Releases

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1316]
MinIO Server [RELEASE.2024-09-09T16-59-28Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-09-09T16-59-28Z) has changes that impact the docs:

- [x] Adds two new config/envvar options for setting up retry intervals for webhook events ([PR #20402](https://github.com/minio/minio/pull/20402))

MinIO Client [RELEASE.2024-09-09T07-53-10Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-09-09T07-53-10Z) has changes that impact the docs:

- [x] `mc idp ldap accesskey` now has three additional subcommands ([PR #5033](https://github.com/minio/mc/pull/5033))
- [x] Output now indicates skipped entries during ILM import ([PR #5032](https://github.com/minio/mc/pull/5032))
