### ISSUE TITLE
[RELEASE] mc  RELEASE.2024-10-02T08-27-28Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1334]
mc [RELEASE.2024-10-02T08-27-28Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-10-02T08-27-28Z) has changes that impact the docs:

- [x] Adds a `--checksum` flag to several commands ([PR #5043](https://github.com/minio/mc/pull/5043))
- [x] Adds `--disable-multipart` to `mc put` ([PR #5041](https://github.com/minio/mc/pull/5041))
- [x] Updates output for `mc ready` ([PR #5044](https://github.com/minio/mc/pull/5044))
- [x] UX changes for `mc admin heal` ([PR #5052](https://github.com/minio/mc/pull/5052))
