### ISSUE TITLE
[RELEASE] MinIO Client RELEASE.2024-10-29T15-34-59Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1361]
MinIO Client [RELEASE.2024-10-29T15-34-59Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-10-29T15-34-59Z) has changes that impact the docs:

- [x] Adds new `mc support top rpc` subcommand ([PR #5060](https://github.com/minio/mc/pull/5060))
       See also [PR #5064](https://github.com/minio/mc/pull/5064) for RPC playback.
- [x] Updates to `mc support inspect` ([PR #5062](https://github.com/minio/mc/pull/5062))
- [x] Adds JSON output for global flag to `mc pipe` ([PR #5065](https://github.com/minio/mc/pull/5065))

**Comment by djwfyi** [comment]
Not doing anything with 5065.
Previously `mc pipe --json` didn't do anything, now it does.
That's a global flag, so nothing really to add anywhere.
