### ISSUE TITLE
[RELEASE] Console v1.7.4

### ISSUE THREAD

**Issue by bexsoft** [minio/docs#1372]
Console Release v1.7.4 does the following breaking changes in the UI

- [ ] Deprecated Lifecycle & Tiering UI [PR #3470](https://github.com/minio/console/pull/3470)
- [ ] Deprecated Site Replication UI [PR #3469](https://github.com/minio/console/pull/3469)
- [ ] Removed SUBNET tools support from UI [PR #3467](https://github.com/minio/console/pull/3467)

Thank you in advance.
