### ISSUE TITLE
[Release] Updates in Operator 0.19.5

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#527]
New functionality has been added in https://github.com/minio/console/releases/tag/v0.19.5 of the Operator.

- [x] Update the appropriate MinIO Operator screen with information on registering tenants by API key. [PR #2222](https://github.com/minio/console/pull/2222/)
- [ ] ~~Operator can now start in DirectPV mode [PR #2203](https://github.com/minio/console/pull/2203)~~
- [x] New fields to support FSGroupChangePolicy when creating a tenant[PR #2233](https://github.com/minio/console/pull/2233)
- [x] When retrieving an API key from Subnet, the tenant can now auto register [PR #2217](https://github.com/minio/console/pull/2217)
- [x] Update screenshots for identity provider reflecting logos [PR #2210](https://github.com/minio/console/pull/2210)
- [x] When creating buckets, updated what is available to use based on permissions [PR #2226](https://github.com/minio/console/pull/2226)
