### ISSUE TITLE
[RELEASE] Console 0.20.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#535]
The [MinIO Console 0.20.0](https://github.com/minio/console/releases/tag/v0.20.0) release has changes that impact the docs:

- [x] Console Support's registration page has been updated with tabs ([#2250](https://github.com/minio/console/pull/2250))
- [x] Metric data can be downloaded as PNG or CSV ([#2241](https://github.com/minio/console/pull/2241))
- [x] Users can now delete configured notification targets in the console ([#2213](https://github.com/minio/console/pull/2213))
