### ISSUE TITLE
[RELEASE]  mc RELEASE.2022-08-23T05-45-20Z doc updates

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#536]
[RELEASE.2022-08-23T05-45-20Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-08-23T05-45-20Z) has changes that impact the docs:

- [x] New flags added to `mc ilm` commands ([PR #4209](https://github.com/minio/mc/pull/4209))
- [x] `mc support top` series of commands ([PR #4201](https://github.com/minio/mc/pull/4201))
- [x] Adds `--with-versioning` flag to `mc mb` ([PR#4216](https://github.com/minio/mc/pull/4216))
- [x] Adds a new `mc od` command ([PR #4180](https://github.com/minio/mc/pull/4180))
- [x] Updates to the `mc support` and `mc license` commands ([PR #4200](https://github.com/minio/mc/pull/4200))
