### ISSUE TITLE
[RELEASE] Console v0.20.1

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#545]
[Console release v0.20.1](https://github.com/minio/console/releases/tag/v0.20.1) has changes that impact the docs:

## Console Changes

- [x] Console **login screen** now supports logging in from multiple Identify providers ([PR #2258](https://github.com/minio/console/pull/2258)) - update screenshots, add info for setting up multiple providers
- [x] The Console's **Logger Webhook** screen now displays configured endpoints ([PR #2279](https://github.com/minio/console/pull/2279)) - update screenshots, add info about the section
- [x] The Console's **Create Bucket** screen now has a dropdown for rules for naming buckets, and there is a validation check ([PR #2262](https://github.com/minio/console/pull/2262))

## Operator Changes

- [x] The Operator's **Tenant Security** page now displays the `FsGroupChangePolicy` in the *Security Context* section ([PR #2252](https://github.com/minio/console/pull/2252)) - check for updated screenshots, add the field
- [x] The Operator now supports uploading client certificates when creating or managing tenants ([PR #2294](https://github.com/minio/console/pull/2294))
