### ISSUE TITLE
[RELEASE] Console Release v0.20.2

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#570]
[Console Release v0.20.2](https://github.com/minio/console/releases/tag/v0.20.2) has changes that impact the docs:

- [x] Console now supports using the `minio` tier type when adding tiers ([PR #2302](https://github.com/minio/console/pull/2302))
- [x] Console now has a logout option when authenticating with OIDC ([PR #2281](https://github.com/minio/console/pull/2281))
- [x] Console buttons have been updated to use mds ([PR #2303](https://github.com/minio/console/pull/2303)). Review all console images for needed screenshot updates.
- [x] When creating a bucket, the screen now has an expanding section to show bucket naming rules ([PR #2311](https://github.com/minio/console/pull/2311)). Verify screenshot(s).

**Comment by djwfyi** [comment]
This work has already been done in other PRs.
Not documenting the OIDC logout option, as we don't document signing out of Console anywhere else, either.
