### ISSUE TITLE
[RELEASE] `mc` RELEASE.2022-09-16T09-16-47Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#571]
The `mc` command line tool has been upgraded to  [RELEASE.2022-09-16T09-16-47Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-09-16T09-16-47Z). 
This bugfix release has changes that impact the docs:

- [x] Adds `--call=healing` to `mc admin trace` ([PR #4229](https://github.com/minio/mc/pull/4229))
- [x] Adds `--request-header` to `mc admin trace` ([PR #4238](https://github.com/minio/mc/pull/4238))
- [x] Allows support for an airgapped URL for `mc update` ([PR #4244](https://github.com/minio/mc/pull/4244))
- [x] Replaces `--storage-class` flags with `--tier` instead for `mc ilm add` command ([PR #4250](https://github.com/minio/mc/pull/4250))
- [x] Check docs for the word `disk(s)` and replace with `drive(s)` for consistency with [PR #4255](https://github.com/minio/mc/pull/4255)

**Comment by djwfyi** [comment]
Note: not documenting the airgapped URL for `mc update` for now.
