### ISSUE TITLE
[RELEASE] mc  RELEASE.2022-10-01T07-56-14Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#602]
`mc` [RELEASE.2022-10-01T07-56-14Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-10-01T07-56-14Z) has changes that impact the docs:

- [x] Check for instances of `disk` or `disks` and replace with `drive` or `drives` for consistency with the product ([PR #4257](https://github.com/minio/mc/pull/4257))
- [x] `mc support perf` generates a .zip file and, if registered with SUBNET and not using the `--airgap` flag, uploads it to SUBNET automatically ([PR #4257](https://github.com/minio/mc/pull/4254))
- [x] Most `mc support` commands now require that the deployment is registered with SUBNET ([PR #4271](https://github.com/minio/mc/pull/4271))
- [x] `mc support diag` no longer includes the `perf` tests, as those have moved to `mc support perf` ([PR #4277](https://github.com/minio/mc/pull/4277))
