### ISSUE TITLE
[RELEASE] Console version v0.21.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#615]
[Console release 0.21.0 ](https://github.com/minio/console/releases/tag/v0.21.0) has changes that impact the docs:

- [ ] The Monitoring > Metrics view now has shows info on server metrics ([PR #2340](https://github.com/minio/console/pull/2340))
- [ ] Users can manually modify the YAML file on the Encryption page when creating a tenant ([PR #2354](https://github.com/minio/console/pull/2354))
- [ ] The Tiers view now hows the status of each tier ([PR #2291](https://github.com/minio/console/pull/2291))
- [ ] Site replication now supports separate accesskey/secretkey for different sites ([PR #2350](https://github.com/minio/console/pull/2350))

**Comment by djwfyi** [comment]
Looks like #2354 has been superseded and the raw YAML option is no longer available in the most recent releases. Not documenting for now.
