### ISSUE TITLE
[Release] mc  RELEASE.2022-11-07T23-47-39Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#636]
mc [RELEASE.2022-11-07T23-47-39Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-11-07T23-47-39Z) has changes that impact the docs:

- [x] Updates the file format output by `mc support inspect` [PR #4185](https://github.com/minio/mc/pull/4185)
- [x] Adds `mc admin rebalance` command [PR #4186](https://github.com/minio/mc/pull/4186) and [PR #15483](https://github.com/minio/minio/pull/15483)
- [x] Adds new commands & subcommands to `mc admin idp` for OIDC or LDAP and deprecates older commands [PR #4310](https://github.com/minio/mc/pull/4310)
- [x] Changes `mc replicate edit` to `mc replicate update` [PR #4346](https://github.com/minio/mc/pull/4346)
