### ISSUE TITLE
[RELEASE] minio RELEASE.2022-11-17T23-20-09Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#644]
Changes to the docs for MinIO [RELEASE.2022-11-17T23-20-09Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-11-17T23-20-09Z)

- [x] For deployments using 3rd party IDp, you can now create service accounts after installation [PR #15939](https://github.com/minio/minio/pull/15939)
- [x] MinIO now supports site level replication resync [PR #15753](https://github.com/minio/minio/pull/15753)
- [x] You can now change the endpoints in distributed setups [PR #16071](https://github.com/minio/minio/pull/16071)

**Comment by ravindk89** [comment]
https://github.com/minio/minio/pull/15939/files is just related to HELM, not new functionality that we need to document.

**Comment by djwfyi** [comment]
Need MC [PR #4269](https://github.com/minio/mc/pull/4269) before we can document `mc admin replicate resync`.
It's merged, but not yet included in a release.
