### ISSUE TITLE
[RELEASE] mc RELEASE.2022-12-02T23-48-47Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#663]
mc [RELEASE.2022-12-02T23-48-47Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-12-02T23-48-47Z) changes that impact the docs:

- [x] Add `mc admin replicate resync` commands (unblocks #644) - [PR #4269](https://github.com/minio/mc/pull/4269/files)
- [x] Adds `mc support proxy` commands - [PR #4375](https://github.com/minio/mc/pull/4375)
- [x] Moves `mc support logs` to `mc admin logs` - [PR #4381](https://github.com/minio/mc/pull/4381)
