### ISSUE TITLE
RELEASE console release  v0.22.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#664]
Console [v0.22.0](https://github.com/minio/console/releases/tag/v0.22.0) has changes that impact the docs:

- [x] Users now see a warning when setting a bucket to public access - [PR #2473](https://github.com/minio/console/pull/2473)
- [x] Login page has new styles - [PR #2467](https://github.com/minio/console/pull/2467)
- [x] Bucket now displays a human readable creation time - PR #2464](https://github.com/minio/console/pull/2464)
- [x] Updates to the Airgap registration page - [PR# 2463](https://github.com/minio/console/pull/2463)

**Comment by djwfyi** [comment]
Bucket display affects a screenshot, but will update in a later pass.
