### ISSUE TITLE
[RELEASE] minio  RELEASE.2022-12-02T19-19-22Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#665]
MinIO [RELEASE.2022-12-02T19-19-22Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-12-02T19-19-22Z) changes that impact the docs:

- [x] Updates the priority of configuration keys when using `mc admin config set ALIAS` - [PR #16150](https://github.com/minio/minio/pull/16150)
- [x] mc now ships with the container version of MinIO - [PR #16156](https://github.com/minio/minio/pull/16156)

MinIO [RELEASE.2022-12-07T00-56-37Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-12-07T00-56-37Z)

- [x] Adds new environment variable related to KES enclaves [PR #16139](https://github.com/minio/minio/pull/16139)
