### ISSUE TITLE
[RELEASE] mc  RELEASE.2022-12-13T00-23-28Z changes that impact the docs

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#685]
The following changes in mc[RELEASE.2022-12-13T00-23-28Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-12-13T00-23-28Z) impact the docs:

- [x] `mc rm --force-delete` is now `mc remove --purge` and is hidden ([PR #4387](https://github.com/minio/mc/pull/4387))
- [x] `mc cp` now has flags for `limit-download`, `limit-upload` ([PR #4388](https://github.com/minio/mc/pull/4388))
- [x] `mc admin bucket quota` moved to `mc quota` ([PR #4389](https://github.com/minio/mc/pull/4389))
- [x] Deprecates `mc admin bucket info` and adds bucket metrics to `mc stat` ([PR #4392](https://github.com/minio/mc/pull/4392))
- [x] Adds `--versions` flag to `mc find` ([PR #4394](https://github.com/minio/mc/pull/4394))
- [x] Adds confirmation prompt when running `mc admin update` ([PR #4400](https://github.com/minio/mc/pull/4400))
- [x] Adds a complete list of call types to help for `mc admin trace` ([PR #4401](https://github.com/minio/mc/pull/4401))
- [x] Adds `mc admin idp ldap policy attach` and `mc admin idp ldap policy detach` commands ([PR #4390](https://github.com/minio/mc/pull/4390))

**Comment by djwfyi** [comment]
`mc rm --force-delete` was not documented. As `--purge` is a hidden flag, also not documenting.

**Comment by djwfyi** [comment]
No changes required for the `mc admin bucket info`, as it was not previously documented and no material changes to the docs for `mc stat` required.
