### ISSUE TITLE
[RELEASE] console v0.22.3 doc impacts

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#686]
Console release [v0.22.3](https://github.com/minio/console/releases/tag/v0.22.3) impacts the docs:

- [x] When creating a tier, the tier type screen now has a help box. Check screenshots ([PR #2519](https://github.com/minio/console/pull/2519))
- [x] Object browser has been separated from the bucket admin ([PR #2500](https://github.com/minio/console/pull/2500))
- [x] IDP screen updated to remove old sections ([PR #2513](https://github.com/minio/console/pull/2513))

**Comment by djwfyi** [comment]
Do not release until a new release of minio later than RELEASE.2022-12-12T19-27-27Z

**Comment by djwfyi** [comment]
Console release 0.22.3 included in minio [RELEASE.2023-01-02T09-40-09Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-01-02T09-40-09Z).
