### ISSUE TITLE
[RELEASE] minio RELEASE.2023-01-02T09-40-09Z doc impacts

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#689]
minio [RELEASE.2023-01-02T09-40-09Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-01-02T09-40-09Z) impacts the docs:

- [x] `host:9000` can now resolve to multiple IPs defined in `/etc/hosts` [PR #16223](https://github.com/minio/minio/pull/16223)
- [x] Remove site replication config (in progress by @ravindk89) [PR #16279](https://github.com/minio/minio/pull/16279)
- [x] Updated list of Prometheus metrics [PR #16329](https://github.com/minio/minio/pull/16329)

Three PRs add API endpoints:
- [x] Manage IAM policies [PR #15897](https://github.com/minio/minio/pull/15897)
- [x] Fetch Policy users and groups [PR #16239](https://github.com/minio/minio/pull/16239)
- [x] Adds STS info command to the API [PR #16115](https://github.com/minio/minio/pull/16115)

**Comment by djwfyi** [comment]
Site replication addressed in #694.
APIs don't affect the docs after all.
