### ISSUE TITLE
[RELEASE] mc RELEASE.2022-12-24T15-21-38Z impacts the docs

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#691]
mc [RELEASE.2022-12-24T15-21-38Z](https://github.com/minio/mc/releases/tag/RELEASE.2022-12-24T15-21-38Z) impacts the docs:

- [x] Updated messaging on disk healing, check for docs [PR #4413](https://github.com/minio/mc/pull/4413)
- [x] `mc replicate status` now shows the remote endpoint [PR #4412](https://github.com/minio/mc/pull/4412)
- [x] ILM commands have been reorganized [PR #4385](https://github.com/minio/mc/pull/4385)
   Covered separately in #662 
- [x] `mc replicate add | update` now includes remote targets (moved out of `mc admin bucket remote`) [PR #4403](https://github.com/minio/mc/pull/4403)
- [x] new filter options added to ~`mc stat`~ `mc admin trace` [PR #4353](https://github.com/minio/mc/pull/4353)

**Comment by djwfyi** [comment]
`mc replicate` command changes addressed by #681 .
