### ISSUE TITLE
[RELEASE] Console version v0.23.1

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#733]
Console [Version v0.23.1](https://github.com/minio/console/releases/tag/v0.23.1) has changes that impact the docs:

- [x] Add a runtime configuration selector and move input box behind it when adding a server pool to a tenant [PR #2626](https://github.com/minio/console/pull/2626)
- [x] Buckets allow anonymous access [PR #2600](https://github.com/minio/console/pull/2600)
- [x] Audit Logs and Monitoring disabled by default for new tenants [PR #2632](https://github.com/minio/console/pull/2632)
- [x] Exposes expiring server certificates [PR #2628](https://github.com/minio/console/pull/2628)
- [x] `Notifications` tab renamed to `Events` [PR #2639](https://github.com/minio/console/pull/2639)
- [x] Updates to capabilities in `Settings > Logger Webhooks` and `Settings > Audit Webhooks` [PR #2620](https://github.com/minio/console/pull/2620)

**Comment by djwfyi** [comment]
#2600 is already sufficiently documented in the existing `managing objects` doc.

**Comment by djwfyi** [comment]
#2620 does not have changes that require updates to the docs at this time, as those screens are not documented in detail.
