### ISSUE TITLE
[RELEASE] mc  RELEASE.2023-02-16T19-20-11Z 

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#736]
`mc` [RELEASE.2023-02-16T19-20-11Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-02-16T19-20-11Z) has updates that impact the docs.

- [x] `mc rm` no longer allows the `--purge` command with any flag other than `--force` [PR #4467](https://github.com/minio/mc/pull/4467)
- [x] `mc admin bucket remote bandwidth` moved into `mc replicate status` command [PR #4430](https://github.com/minio/mc/pull/4430)
- [ ] new `mc admin user sts info` command [PR #4377](https://github.com/minio/mc/pull/4377)

**Comment by djwfyi** [comment]
`mc admin bucket remote bandwidth` was not documented, but added a version changed note to the `mc admin bucket remote` page.

**Comment by djwfyi** [comment]
`mc rm --purge` flag not documented.

**Comment by djwfyi** [comment]
PR #4377 to be documented by @ravindk89 .
