### ISSUE TITLE
[RELEASE] minio RELEASE.2023-02-27T18-10-45Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#746]
MinIO release [RELEASE.2023-02-27T18-10-45Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-02-27T18-10-45Z) has changes that impact the docs:

- [x] Add information about OpenID redirects [PR #16704](https://github.com/minio/minio/pull/16704)
- [x] New metrics for custom auth plugin [PR #16701](https://github.com/minio/minio/pull/16701)
- [x] MinIO now supports adding service accounts with expiration (currently by SDK only) [PR #16430](https://github.com/minio/minio/pull/16430)

**Comment by ravindk89** [comment]
#476 is integrating 16704 as part of ongoing work.
