### ISSUE TITLE
[RELEASE] Console v0.24.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#747]
Console [v0.24.0](https://github.com/minio/console/releases/tag/v0.24.0) has changes that impact the docs:

- [x] Enable/disable Call Home [PR #2248](https://github.com/minio/console/pull/2248)
- [x] Tooltips show environment variable for settings [PR #2636](https://github.com/minio/console/pull/2636)
- [x] Export/Import server configuration settings [PR #2664](https://github.com/minio/console/pull/2664)
- [x] Health component removed [PR #2659](https://github.com/minio/console/pull/2659)
- [x] Object Manager button restored [2665](https://github.com/minio/console/pull/2665)

**Comment by djwfyi** [comment]
Note: 2659 did not require changes to the Console pages.
