### ISSUE TITLE
[RELEASE] mc  RELEASE.2023-03-20T17-17-53Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#766]
mc [RELEASE.2023-03-20T17-17-53Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-03-20T17-17-53Z) has changes that impact the docs:

- [x] `mc support proxy set|remove` no longer required an active SUBNET registration, since setting the proxy may be required in order to register ([PR #4488](https://github.com/minio/mc/pull/4488))
- [x] `replicate status` has had updates to info that displays from stale ARNs ([PR #4494](https://github.com/minio/mc/pull/4494))
- [x]  when runing `mc rm --dry-run` with certain flags, additional modtime information now displays ([PR #4495](https://github.com/minio/mc/pull/4495))
- [x] BREAKING CHANGES `mc policy` commands have been renamed, new `mc admin policy entities` added ([PR #4428](https://github.com/minio/mc/pull/4428))
- [x] Batch jobs can now be canceled with `mc batch cancel` ([mc PR #4506](https://github.com/minio/mc/pull/4506), [MinIO PR #16843](https://github.com/minio/minio/pull/16843))

NOTE: This release has breaking changes related to the `mc policy` commands.
Requires MinIO [RELEASE.2023-03-20T20-16-18Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-20T20-16-18Z).
