### ISSUE TITLE
[RELEASE] MinIO  RELEASE.2023-03-20T20-16-18Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#767]
MinIO [RELEASE.2023-03-20T20-16-18Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-20T20-16-18Z) has changes that impact the docs:

- [ ] Pools with tiered content can now be decommissioned ([PR #16751](https://github.com/minio/minio/pull/16751))
- [ ] LDAP IDP can now be enabled or disabled with a flag ([PR #16805](https://github.com/minio/minio/pull/16805))
- [ ] Adds support for batch job cancellation (requires mc [RELEASE.2023-03-20T17-17-53Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-03-20T17-17-53Z)) 
see related docs issue #766 
- [ ] Object names on Windows cannot have a `\` character ([PR #16856](https://github.com/minio/minio/pull/16856))

**Comment by djwfyi** [comment]
Batch cancelation added with #766.
