### ISSUE TITLE
[RELEASE] console v0.26.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#788]
Console [v0.26.0](https://github.com/minio/console/releases/tag/v0.26.0) has changes that impact the docs:

- [x] Audit Kafka tab added to the MinIO Configuration ([PR #2724](https://github.com/minio/console/pull/2724))
- [x] Add anonymous access to prefixes ([PR #2736](https://github.com/minio/console/pull/2736))
- [x] Generate and upload health reports to SUBNET ([PR #2606](https://github.com/minio/console/pull/2606))

## Non-goals

- This is not the time to document Kafka.
- There is not currently a place to link to for more Kafka - MinIO info in the docs.

**Comment by djwfyi** [comment]
Anonymous access for prefixes is already mentioned in the existing docs, nothing changed for this issue.
