### ISSUE TITLE
[RELEASE] Operator v5.0.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#791]
Operator [v5.0.0](https://github.com/minio/operator/releases/tag/v5.0.0) has changes that impact the docs:

- [x] Now supports [Workload identities](https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity) for KES + GKE ([PR #1501](https://github.com/minio/operator/pull/1501))
- [x] Creates operator environment variables ([PR #1518](https://github.com/minio/operator/pull/1518))
- [x] TLS moved from operator to the sidecar ([PR #1515](https://github.com/minio/operator/pull/1515))
       - see also the updated Operator TLS docs as changed in [PR #1473](https://github.com/minio/operator/pull/1473)
- [x] Generate and download tenant reports ([PR #1498](https://github.com/minio/operator/pull/1498))
- [x] Operator now utilizes separate `initContainer` and `sidecar` containers ([PR #1437](https://github.com/minio/operator/pull/1437))
- [x] Additional support for Openshift for the `kubectl proxy` command ([PR #1431](https://github.com/minio/operator/pull/1431))
- [x] New tenants now have the audit logs and prometheus disabled by default (this deprecation was previously announced) ([PR #1433](https://github.com/minio/operator/pull/1433))

- [x] Operator 5.0.2 added documentation for how to continue using prometheus and audit logs after upgrading ([PR #1525](https://github.com/minio/operator/pull/1525))
