### ISSUE TITLE
[RELEASE] minio RELEASE.2023-04-07T05-28-58Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#806]
MinIO [RELEASE.2023-04-07T05-28-58Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-04-07T05-28-58Z) has changes that impact the docs:

- [ ] A new environment variable `MINIO_ILM_EXPIRY_WORKERS` to define workers to use for ILM expiration ([PR #16924](https://github.com/minio/minio/pull/16924))
- [ ] Batch replicate can be used from remote MinIO to local ([PR #16922](https://github.com/minio/minio/pull/16922))
- [ ] Three new metrics added for tracking object locks ([PR #16943](https://github.com/minio/minio/pull/16943))
- [ ] `mc batch` can now automate key rotation for objects with existing, expiring keys ([PR #16844](https://github.com/minio/minio/pull/16844))
