### ISSUE TITLE
[RELEASE] mc RELEASE.2023-04-12T02-21-51Z doc changes

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#815]
mc [RELEASE.2023-04-12T02-21-51Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-04-12T02-21-51Z) has changes that impact the docs:

- [x] `mc stat` now prints restore info for tiered objects ([PR #4534](https://github.com/minio/mc/pull/4534))
- [x] `mc admin replicate update` can now enable and disable synchronous mode ([PR #4514](https://github.com/minio/mc/pull/4514))
- [x] Adds metadata and tags to `mc find` ([PR #4531](https://github.com/minio/mc/pull/4531))
