### ISSUE TITLE
[RELEASE] MinIO RELEASE.2023-05-04T21-44-30Z doc changes

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#845]
MinIO [RELEASE.2023-05-04T21-44-30Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-05-04T21-44-30Z) has changes that impact the docs:

- [x] `root` can now be disabled in config settings ([PR #17089](https://github.com/minio/minio/pull/17089))
- [x] Support for systemd notification protocol ([PR #17062](https://github.com/minio/minio/pull/17062))
- [x] Directory objects no longer create new versions ([PR #17109](https://github.com/minio/minio/pull/17109))
- [x] Batch replication supports arbitrary s3 source or target ([PR #17113](https://github.com/minio/minio/pull/17113))
- [ ] Added support for virtual routing and forwarding on Linux ([17108](https://github.com/minio/minio/pull/17108))
- [x] New environment variable to control console animation ([PR #17123](https://github.com/minio/minio/pull/17123))
        See also [Console PR #2799](https://github.com/minio/console/pull/2799)
- [x] Allow directory deletes to perform permanent deletes ([PR #17132](https://github.com/minio/minio/pull/17132))
- [x] EC:0 value not allowed except at server startup ([PR #17141](https://github.com/minio/minio/pull/17141))

**Comment by ravindk89** [comment]
@harshavardhana how much attention do we want to draw to the VRF ability? It's marked as a hidden CLI/ENVVAR, but we can document at least the `--interface` flag. Not sure if the user timeout flag needs visibility if it's mostly internal
