### ISSUE TITLE
[RELEASE] mc RELEASE.2023-05-04T18-10-16Z doc changes

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#846]
mc [RELEASE.2023-05-04T18-10-16Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-05-04T18-10-16Z) has changes that impact the docs.

- [ ] Adds support for two new architectures ([PR #4549](https://github.com/minio/mc/pull/4549))
- [x] Makes `ls` and `rm` subcommands consistent across all commands ([PR #4548](https://github.com/minio/mc/pull/4548))
- [x] `iam export` allows for aliases to end in a `/` character ([PR #4554](https://github.com/minio/mc/pull/4554))
- [x] `mc tag remove` can now remove tags from all versions ([PR #4563](https://github.com/minio/mc/pull/4563))
- [x] Breaking change to how `mc mirror --remove` works for paths to directories that do not end in a `/` ([PR #4560](https://github.com/minio/mc/pull/4560))

**Comment by ravindk89** [comment]
Note that LoongArch is associated with Loongson, which is [Blacklisted by the US Department of Commerce](https://www.tomshardware.com/news/us-govt-blacklists-loongson-and-inspur).

We will not officially document support for this architecture.
