### ISSUE TITLE
[Release] mc RELEASE.2023-05-18T16-59-00Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#859]
MinIO Client [RELEASE.2023-05-18T16-59-00Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-05-18T16-59-00Z) has changes that impact the docs:

- [ ] You can now generate a random secret key for a specified access key when creating a service account ([PR #4565](https://github.com/minio/mc/pull/4565))
- [ ] When adding or editing service accounts, the `--comment` flag has been replaced with `--name` and `--description` flags ([PR #4569](https://github.com/minio/mc/pull/4569))
- [ ] Deprecation notices added to older `mc idp` commands with pointers to replacements ([PR #4572](https://github.com/minio/mc/pull/4572))

**Comment by feorlen** [comment]
https://github.com/minio/mc/pull/4565 is a bug fix, the existing docs are ok. But it would be nice to include detail on generated key length.

**Comment by feorlen** [comment]
Planning to include the `mc admin idp` -> `mc idp` part from https://github.com/minio/docs/issues/866 with the `idp` updates from this one. These two changes are related, but landed in different releases.

**Comment by feorlen** [comment]
`idp` portion completed with https://github.com/minio/docs/pull/873
