### ISSUE TITLE
[RELEASE] Console  v0.28.0

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#865]
Console [v0.28.0](https://github.com/minio/console/releases/tag/v0.28.0) has changes that impact the docs:

- [x] ~Users can now share objects using an embedded service account access key [PR #2827](https://github.com/minio/console/pull/2827)~
- [x] Fix for NGINX config for Console at a subpath [PR #2818](https://github.com/minio/console/pull/2818)
- [x] Fix for a potential security issue with the right-to-left unicode character [PR #2828](https://github.com/minio/console/pull/2828)

**Comment by djwfyi** [comment]
PR 2827 is being reverted to implement better a fields and flows. Do not doc.

**Comment by ravindk89** [comment]
Partially addressed with https://github.com/minio/docs/pull/921

**Comment by djwfyi** [comment]
No place to discuss 2828 outside of Github where it's already done.
