### ISSUE TITLE
[RELEASE] mc RELEASE.2023-05-26T23-31-54Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#866]
MinIO Client [RELEASE.2023-05-26T23-31-54Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-05-26T23-31-54Z) has changes that impact the docs:

- [ ] `mc admin idp` has moved to `mc idp` [PR #4574](https://github.com/minio/mc/pull/4574)
- [ ] `mc admin user ls` now shows details of a user's groups and the policies those groups add [PR #4578](https://github.com/minio/mc/pull/4578)
- [ ] `mc ilm` list commands now show when a rule last changed [PR #4579](https://github.com/minio/mc/pull/4579)
- [ ] `mc admin user svcacct list` now shows expiration date information [PR #4576](https://github.com/minio/mc/pull/4576)
