### ISSUE TITLE
[RELEASE] MinIO  RELEASE.2023-05-27T05-56-19Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#867]
MinIO [RELEASE.2023-05-27T05-56-19Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-05-27T05-56-19Z) has changes that impact the docs:

- [x] Batch replication now supports path/virtual style lookup [PR #17201](https://github.com/minio/minio/pull/17201)
- [x] When adding a new webhook, the system now ignores the status of existing webhooks, though target must be online [PR #17250](https://github.com/minio/minio/pull/17250)
- [x] Decommissioning ignores objects with only a single DEL marker [PR #17274](https://github.com/minio/minio/pull/17274)
- [x] `mc admin policy entities` now only returns MinIO IDP policies [PR #17241](https://github.com/minio/minio/pull/17241)
- [x] `mc admin policy attach` now requires that the user exists to restrict it for use with only MinIO IDP [PR #17240](https://github.com/minio/minio/pull/17240)

**Comment by ravindk89** [comment]
- [ ] Needs testing, but list calls may return parity metadata [PR #17238](https://github.com/minio/minio/pull/17238/files)
- [ ] New header `x-minio-fanout-list` for MinIO "Fan Out" extension [PR #17233](https://github.com/minio/minio/pull/17233). Will require engaging with engineers, dev-focused specialty feature

**Comment by ravindk89** [comment]
- [] Test to be sure, but decomm may trigger ILM checks for expiration [PR 17282](https://github.com/minio/minio/pull/17282)

**Comment by ravindk89** [comment]
Note: We already have a doc chunk on ignoring single DEL markers. Waiting for eng. to confirm that this is just a bug fix, or maybe the original docs were incorrect

**Comment by ravindk89** [comment]
Review https://github.com/minio/minio/pull/17482 as part of this

**Comment by ravindk89** [comment]
See #898
