### ISSUE TITLE
[Release] minio server  RELEASE.2023-06-23T20-26-00Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#898]
MinIO Server [RELEASE.2023-06-23T20-26-00Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-06-23T20-26-00Z) has changes that impact the docs:

- [ ] Bucket notifications can now be done synchronously ([PR#17406](https://github.com/minio/minio/pull/17406))
- [x] Decommission process checks expired versions and skips them ([PR #17479](https://github.com/minio/minio/pull/17479))
- [x] Rebalance process checks expired versions and skips them ([PR #17482](https://github.com/minio/minio/pull/17482))
- [x] New metrics added for bucket level API request counts ([PR #17468](https://github.com/minio/minio/pull/17468))
- [ ] Config reporting APIs no longer return secrets ([17380](https://github.com/minio/minio/pull/17380))

**Comment by ravindk89** [comment]
Doing the dcom/rebalance work as part of #888

**Comment by ravindk89** [comment]
@djwfyi doing 17468-related work as part of a metrics pass.
