### ISSUE TITLE
[Release] Operator 5.0.6 changes

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#900]
Operator [v5.0.6](https://github.com/minio/operator/releases/tag/v5.0.6) has changes that impact the docs:

- [x] (Helm) Adds support for custom extra resources to add to the container ([PR #1643](https://github.com/minio/operator/pull/1643))
- [x] MinIO can now run in restricted namespaces ([PR #1651](https://github.com/minio/operator/pull/1651))
- [x] Feature: Adds support for [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) ([PR #1644](https://github.com/minio/operator/pull/1644))
- [x] (Helm) Adds example to the yaml for bucket schemas ([PR #1657](https://github.com/minio/operator/pull/1657))

**Comment by djwfyi** [comment]
@feorlen checking on the Helm stuff, please.

**Comment by feorlen** [comment]
https://github.com/minio/operator/pull/1657 doesn't appear to require any additional docs.

Docs don't cover the structure or contents of Helm charts other than to say you can modify them as needed. We link to Helm docs and presume anyone who does that is familiar with the format. And they will see this comment when they get there.

**Comment by feorlen** [comment]
For https://github.com/minio/operator/pull/1643, following up with Engineering about adding an example for this in the YAML file. The docs don't currently cover how to modify the Helm chart, and this appears to be a fairly uncommon use case.

**Comment by feorlen** [comment]
Note: current docs have a single mention of init containers https://min.io/docs/minio/kubernetes/upstream/operations/installation.html#minio-operator-components

**Comment by pjuarezd** [comment]
> 

This would be an practical example
https://github.com/minio/operator/pull/1739

**Comment by feorlen** [comment]
Helm `extraResources` (https://github.com/minio/operator/pull/1643) handled with a comment in the Helm chart.

See https://github.com/minio/operator/pull/1739
