### ISSUE TITLE
[RELEASE] minio 2023-07-21T21-12-44Z and 2023-07-18T17-49-40Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#931]
Two MinIO Server releases have changes that impact the docs:

## [RELEASE.2023-07-18T17-49-40Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-07-18T17-49-40Z)

- [x] Re-queuing of failed replication requests limited to 3 retries ([PR #17171](https://github.com/minio/minio/pull/17171))
- [x] MinIO can now actively take disks offline when it detects that `write` and `read` operations cannot complete ([PR #17539](https://github.com/minio/minio/pull/17539))

       Low priority; check with Klaus; move to slushpile if not done with this issue
- [x] Add count of delete markers to admin info ([PR #17659](https://github.com/minio/minio/pull/17659))

## [RELEASE.2023-07-21T21-12-44Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-07-21T21-12-44Z)

- [x] Bucket metrics moved to a new endpoint ([PR #17663](https://github.com/minio/minio/pull/17663))
- [x] Grafana dashboard updated with new metrics ([PR #17683](https://github.com/minio/minio/pull/17683))
- [x] New Prometheus metrics delete marker metric ([PR #17689](https://github.com/minio/minio/pull/17689))

**Comment by ravindk89** [comment]
- https://min.io/docs/minio/linux/administration/bucket-replication.html#replication-process
- https://min.io/docs/minio/linux/operations/monitoring/metrics-and-alerts.html#minio-console-metrics-dashboard <- maybe dedicated section for grafana now?

**Comment by ravindk89** [comment]
Doing this might close #864

**Comment by djwfyi** [comment]
See also #864

**Comment by djwfyi** [comment]
See also https://github.com/minio/minio/pull/17727

**Comment by djwfyi** [comment]
Working on 17683

**Comment by djwfyi** [comment]
On 17683, I don't think it's worth trying to keep the Grafana overview page I'm adding updated with each individual change made to the dashboard. The new overview page has a link to the GitHub json files. That should suffice.

**Comment by djwfyi** [comment]
Partially addressed in #953

**Comment by feorlen** [comment]
Per Klaus, https://github.com/minio/minio/pull/17539 has nothing new to add. This is just another way to determine a disk failure happened and report accordingly.
