### ISSUE TITLE
[Release] MinIO Server RELEASE.2023-08-04T17-40-21Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#938]
MinIO Server [RELEASE.2023-08-04T17-40-21Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-08-04T17-40-21Z) has changes that impact the docs:

- [x] New bucket metrics added to Grafana dashboard ([PR #17727](https://github.com/minio/minio/pull/17727))
        See also #864, #931 for related bucket metric work
- [x] Adds a deadline for READ operations ([PR #17724](https://github.com/minio/minio/pull/17724))
- [x] Cluster health exports to Prometheus metrics ([PR #17741](https://github.com/minio/minio/pull/17741))
- [x] Adds two new disk metrics ([PR #17748](https://github.com/minio/minio/pull/17748))
- [x] Adds limit of 10,000 object versions ([PR #17803](https://github.com/minio/minio/pull/17803))
- [x] Adds low drive timeouts to disk monitoring ([PR #17701](https://github.com/minio/minio/pull/17701))

**Comment by djwfyi** [comment]
After internal discussion, not documenting 17724 or 17701 at this time.

**Comment by djwfyi** [comment]
17724 and 17748 previously addressed with #864 .
