### ISSUE TITLE
[RELEASE] Operator v5.0.7 doc updates

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#943]
Operator [v5.0.7](https://github.com/minio/operator/releases/tag/v5.0.7) has changes that impact the docs:

- [x] `kubectl minio tenant info` now includes tenant secret info ([PR #1704](https://github.com/minio/operator/pull/1704))
- [ ] Can now mount volumes to the Operator pod ([PR #1700](https://github.com/minio/operator/pull/1700))
- [x] Add SFTP support during tenant creation ([PR #1685](https://github.com/minio/operator/pull/1685) and [PR #1692](https://github.com/minio/operator/pull/1692)) (Existing Tenants also)
- [x] `kubectl minio delete` now has a `--force` flag ([PR #1687](https://github.com/minio/operator/pull/1687))

Helm changes:

- [x] Support `digest` for OpenShift [PR #1706](https://github.com/minio/operator/pull/1706)
- [x] The helm chart has been split into separate files as per best practices [PR #1677](https://github.com/minio/operator/pull/1677)

**Comment by feorlen** [comment]
https://github.com/minio/operator/pull/1677 doesn't require doc updates at this time. 

Specifics of chart structure/contents will get covered in a future section about how to customize. For now we link to the relevant Helm docs and presume anyone needing this level of customization already knows how charts work.

**Comment by feorlen** [comment]
Similar to previous, no doc updates needed for https://github.com/minio/operator/pull/1706

The new option is documented with a comment in `operator/values.yaml`.

**Comment by djwfyi** [comment]
Last item relates to Helm charts, which are not documented.
Also waiting for feedback on the PR 1700 about the use case.

**Comment by feorlen** [comment]
Requested use case details for https://github.com/minio/operator/pull/1700. We are unclear about their intended purpose that needed this functionality.
